### ISSUE TITLE
Add Supernatural (TV)

### ISSUE THREAD

**Issue by brittanyrw** [brittanyrw/emojiscreen#100]
Add Supernatural to EmojiScreen.

Link:  https://www.imdb.com/title/tt0460681/

**Comment by navneetsharmaui** [comment]
@brittanyrw I will resolve this issue.

**Comment by navneetsharmaui** [comment]
@brittanyrw I will do this, assign it to me

**Comment by navneetsharmaui** [comment]
> @brittanyrw I will do this, assign it to me

@brittanyrw Can I start on this?

**Comment by brittanyrw** [comment]
Hi @navneetsharmaui It looks like someone already added this show 5 days ago and the Issue wasn't closed yet. I am going to close the Issue now. Sorry about that, feel free to add something else instead.
