### ISSUE TITLE
Organize CSS file

### ISSUE THREAD

**Issue by brittanyrw** [brittanyrw/emojiscreen#105]
Organize the `main.css` file and add comments so that it is easy to tell what CSS goes with each section of the website.

**Comment by catherineleung** [comment]
Hi! Can I work on this issue for Hacktoberfest? :)

**Comment by ghost** [comment]
Hi, do you want comments to explain what each section in the `main.css` file does to the elements of the website?

**Comment by catherineleung** [comment]
#603 Completed
