### ISSUE TITLE
Add Bring it On (Movie)

### ISSUE THREAD

**Issue by brittanyrw** [brittanyrw/emojiscreen#112]
Add Bring it on to EmojiScreen.

Link: https://www.imdb.com/title/tt0204946/

**Comment by navneetsharmaui** [comment]
@brittanyrw I will do this as for two the Issues that I applied for, has been done by some one.

**Comment by navneetsharmaui** [comment]
@brittanyrw assign this to me. before this also is taken by someone else 😂
