### ISSUE TITLE
Add a search bar under the filters on the EmojiScreen homepage

### ISSUE THREAD

**Issue by brittanyrw** [brittanyrw/emojiscreen#113]
Add a search bar so that users can search for specific movies or shows on the homepage.

**Comment by dlhrubin** [comment]
Hi! I've started working on this and was wondering if you could assign this to me.

**Comment by brittanyrw** [comment]
Sure! Thanks for working on this.

**Comment by dlhrubin** [comment]
Quick question: which browsers should EmojiScreen support? I wanted to use an element (datalist) that appears to be buggy in Edge, so I'm considering implementing my own version of this feature instead.

**Comment by brittanyrw** [comment]
@dlhrubin I think that will be fine. It doesn't look like many people are using Edge when looking at the site right now. This is the Google Analytics from launch until now:

<img width="781" alt="Screen Shot 2019-09-05 at 5 40 38 PM" src="https://user-images.githubusercontent.com/23530405/64385404-5cfc5c80-d004-11e9-8050-2ad0d6bb769c.png">

We can always address it later if it becomes an issue.

**Comment by mzeenkala23** [comment]
is this issue still open
