### ISSUE TITLE
Add Law and Order (TV Show)

### ISSUE THREAD

**Issue by brittanyrw** [brittanyrw/emojiscreen#116]
Add Law and Order to EmojiScreen.
Link: https://www.imdb.com/title/tt0098844/

**Comment by denverlisa** [comment]
I will add this one.

**Comment by RahulRavishankar** [comment]
I would like to work on it!

**Comment by brittanyrw** [comment]
@RahulRavishankar Someone else has already commented in this Issue. Please choose something else to add. Thanks!
