### ISSUE TITLE
Add instructions for creating a branch to README

### ISSUE THREAD

**Issue by brittanyrw** [brittanyrw/emojiscreen#133]
Add instructions to the Github UI and the Local Environment sections for creating a branch.

For Github UI - Add instructions for creating a branch during the pull request step. 
For Local Environment - add instructions for creating a branch in the terminal after they clone the repo.

**Comment by kwaimind** [comment]
Hey, I think I can take this if you need some help. 

Just to be clear, you want a simple guide on how to make a pull request in the GitHub app AND the cli?

**Comment by brittanyrw** [comment]
@kwaimind I want to add instructions on how to create a branch for your pull request, in this section: https://github.com/brittanyrw/emojiscreen#walkthrough

Right now it doesn't say to make a branch so everyone is just using master. 

Probably around/after step number 6 in both the 'GitHub UI' (which is just the Github website) and 'Local Development' sections.

Similar to this repo's instructions: https://github.com/firstcontributions/first-contributions
