### ISSUE TITLE
Add button to increase the size of the emoji images

### ISSUE THREAD

**Issue by brittanyrw** [brittanyrw/emojiscreen#135]
EmojiScreen now has four columns across so less scrolling is needed to see the EmojiCards. The size of each individual emoji had to be reduced a little to fit into four columns.

So now we should add a button (same area where the expand all button is) that a user can click to make the size of the emoji images larger so they are easier to see. 

One possible solution is when the button is clicked, add a class to the container with the id of `emojis`. Toggle that class on and off when the button is clicked. This class should increase the image size as well as decrease the number of columns. 

So as an example, make the image size 50px and also change the grid-template-columns from `grid-template-columns: 1fr 1fr 1fr 1fr;` `to grid-template-columns: 1fr 1fr`; instead. 

The column size will need to decrease when the image size increases because otherwise the emojis will end up taking up two lines instead of one. We want to keep the emojis all on one line.

**Comment by ghost** [comment]
Hi. May I give it a try?

**Comment by brittanyrw** [comment]
Hi @mjfneto. Sorry about that, I am just now seeing your comment. Did you still want to work on this?

**Comment by ghost** [comment]
Sure. May I?
