### ISSUE TITLE
Add all of the Iron Man movies and review existing Iron Man cards

### ISSUE THREAD

**Issue by brittanyrw** [brittanyrw/emojiscreen#136]
Make sure that all of the Iron Man movies have been added to EmojiScreen and review the emojis in existing ones to make sure they make sense/are descriptive enough for people to guess when we have game mode created. 

Iron Man (2008)
Iron Man 2 (2010)
Iron Man 3 (2013)

List of Iron Man Movies: https://www.imdb.com/list/ls031270252/

**Comment by Kesav4** [comment]
Hello!..I would like to take this one
