### ISSUE TITLE
Add all of the Captain America movies and review existing Captain America cards

### ISSUE THREAD

**Issue by brittanyrw** [brittanyrw/emojiscreen#137]
Make sure that all of the main Captain America movies have been added to EmojiScreen and review the emojis in existing ones to make sure they make sense/are descriptive enough for people to guess when we have game mode created. 

Captain America: The First Avenger (2011): https://www.imdb.com/title/tt0458339/
Captain America: The Winter Soldier (2014): https://www.imdb.com/title/tt1843866/
Captain America: Civil War (2016): https://www.imdb.com/title/tt3498820/

**Comment by navneetsharmaui** [comment]
I will do this task.

**Comment by navneetsharmaui** [comment]
@brittanyrw  Assign me this issue.

**Comment by navneetsharmaui** [comment]
@brittanyrw As discussed I've commented on the issues that I want to resolve. Assign me this issue.
