### ISSUE TITLE
Add all of the Thor movies and review existing Thor cards

### ISSUE THREAD

**Issue by brittanyrw** [brittanyrw/emojiscreen#138]
Make sure that all of the main Thor movies have been added to EmojiScreen and review the emojis in existing ones to make sure they make sense/are descriptive enough for people to guess when we have game mode created.

Thor (2011): https://www.imdb.com/title/tt00000800369/
Thor: The Dark World (2013): https://www.imdb.com/title/tt1981115/
Thor: Ragnarok (2017): https://www.imdb.com/title/tt3501632/

**Comment by aflussing** [comment]
Hey! Can I do this one?
