### ISSUE TITLE
Add all of the Guardians of the Galaxy movies and review existing Guardians of the Galaxy cards

### ISSUE THREAD

**Issue by brittanyrw** [brittanyrw/emojiscreen#139]
Make sure that all of the main Guardians of the Galaxy movies have been added to EmojiScreen and review the emojis in existing ones to make sure they make sense/are descriptive enough for people to guess when we have game mode created.

Guardians of the Galaxy (2014): https://www.imdb.com/title/tt2015381/
Guardians of the Galaxy Vol. 2 (2017): https://www.imdb.com/title/tt3896198/

**Comment by lsfernandes92** [comment]
Hi, I am Groot!?

**Comment by lsfernandes92** [comment]
Ops... I've forgotten the translation. Big fan of Guardians of the Galaxy here, could I take it? :D

**Comment by brittanyrw** [comment]
@lsfernandes92 Yep, thanks for working on this!
