### ISSUE TITLE
Add additional Marvel movies (Hulk, Ant-Man, Dr. Strange, Captain Marvel, etc)

### ISSUE THREAD

**Issue by brittanyrw** [brittanyrw/emojiscreen#143]
Make sure that the rest of the MCU movies have been added to EmojiScreen and review the emojis in existing ones to make sure they make sense/are descriptive enough for people to guess when we have game mode created.

The Incredible Hulk (2008) https://www.imdb.com/title/tt0800080/
Ant-Man (2015) https://www.imdb.com/title/tt0478970/
Doctor Strange (2016) https://www.imdb.com/title/tt1211837/
Ant-Man and the Wasp (2018) https://www.imdb.com/title/tt5095030/
Captain Marvel (2019) https://www.imdb.com/title/tt4154664/

Check the issues for additional Marvel movies to add!

**Comment by MaximeKoitsalu** [comment]
I'd be glad to take on this issue
