### ISSUE TITLE
Convert jQuery to vanilla JavaScript in app.js

### ISSUE THREAD

**Issue by brittanyrw** [brittanyrw/emojiscreen#156]
1. Change the jQuery code in app.js to vanilla JavaScript. 
2. Add additional comments explaining what the code is doing if needed. 
3. Remove the jQuery link in the index.html file.

**Comment by Seniru** [comment]
OK, I'll be working on this 💪

**Comment by brittanyrw** [comment]
Awesome, thanks for working on this!
