### ISSUE TITLE
Add Pagination to EmojiScreen homepage

### ISSUE THREAD

**Issue by brittanyrw** [brittanyrw/emojiscreen#199]
Add pagination to the homepage.

- [ ] On the homepage, a maximum of 30 cards should show. After 30, user should be able to click to go to 'page 2' to show another 30 cards. 
- [ ] Pagination should be at the bottom of the page, above the footer section.
- [ ] Consider how the pagination will work with the filters. 
- [ ] Style using existing colors and fonts. 

Similar to the attached image (design does NOT have to match the image, just showing what I mean by pagination). 
![pagination_1 1785fc69](https://user-images.githubusercontent.com/23530405/64180850-7d28f180-ce33-11e9-8bb6-aab2a309efa3.png)

**Comment by proabel** [comment]
I will work on this.

**Comment by proabel** [comment]
Is this design ok ?

![pagination](https://user-images.githubusercontent.com/44163332/64261304-f0248c00-cf49-11e9-9521-c3222c7e2777.PNG)

**Comment by brittanyrw** [comment]
@proabel that looks great! 

I just realized that I said show 30 per page, in that case we can change the columns to three columns instead of four so there won't be weird empty spaces, once the pagination is added in.

Did you want to add that into what you are working with now? Or I can create a new issue for that CSS update.

**Comment by proabel** [comment]
@brittanyrw if we want three columns then do we need to resize (increase) the emoji-cards to match the present row width. Or we can leave it as it is and row gets thinner. Or simply we can change the count to 32. how to proceed?

Yeah! you can add that to this same issue.

**Comment by brittanyrw** [comment]
@proabel Ah yes, you are right. Let's keep it at 30 and make the images bigger.

**Comment by proabel** [comment]
@brittanyrw  Hi I could not create a pull request the "create pull request" button is disabled. Any idea on this?

**Comment by proabel** [comment]
@brittanyrw I have given the pull request.

**Comment by adriancova** [comment]
@brittanyrw Hi, is this issue resolved? The changes seem to be completed based on the conversation but I don't see them reflected on the website.
