### ISSUE TITLE
Add all of the Indiana Jones movies and review existing Indiana Jones cards

### ISSUE THREAD

**Issue by brittanyrw** [brittanyrw/emojiscreen#209]
Make sure that all of the Indiana Jones movies have been added to EmojiScreen and review the emojis in existing ones to make sure they make sense/are descriptive enough for people to guess when we have game mode created.

List of Indiana Jones Movies: https://www.imdb.com/list/ls053788854/

**Comment by Jashaul** [comment]
I would like to work on this issue
