### ISSUE TITLE
Add all of the Fantastic Beasts movies and review existing Fantastic Beasts cards

### ISSUE THREAD

**Issue by brittanyrw** [brittanyrw/emojiscreen#210]
Make sure that all of the Fantastic Beasts movies have been added to EmojiScreen and review the emojis in existing ones to make sure they make sense/are descriptive enough for people to guess when we have game mode created.

Fantastic Beasts and Where to Find Them (2016): https://www.imdb.com/title/tt3183660/
Fantastic Beasts: The Crimes of Grindelwald (2018): https://www.imdb.com/title/tt4123430/

**Comment by zplusp** [comment]
Can I take this one ?
