### ISSUE TITLE
Add Annie (Movie)

### ISSUE THREAD

**Issue by brittanyrw** [brittanyrw/emojiscreen#218]
Add Annie to EmojiScreen
Link: https://www.imdb.com/title/tt0083564/

**Comment by TerminalGhost915** [comment]
Hi,new to open source contribution . There is a separate movie having the same tittle Annie (2014) IMDB : https://www.imdb.com/title/tt1823664/

**Comment by brittanyrw** [comment]
@BishwajitPaul Yep! We can make a new issue for the other Annie movies, I think there are at least three. It's okay if the same movie is added, as long as it is a different version. 

Let me know if you'd like to make the issue with the 2014 Annie movie or I can make it. Then we'd update this one to specify 1982 as the year.

**Comment by the-bose** [comment]
Hello, I would like to work on this for hacktoberfest
