### ISSUE TITLE
Add all of the James Bond movies and review existing James Bond cards

### ISSUE THREAD

**Issue by brittanyrw** [brittanyrw/emojiscreen#227]
Make sure that all of the James Bond movies have been added to EmojiScreen and review the emojis in existing ones to make sure they make sense/are descriptive enough for people to guess when we have game mode created.

Link to all James Bond movies: https://www.imdb.com/list/ls004489992/

**Comment by rubiin** [comment]
@brittanyrw i will take it

**Comment by brittanyrw** [comment]
@rubiin Thanks, for working on this. 

However since Hacktoberfest is coming and many people more people will most likely want to work on tis project as well, I am limiting the number of Issues that can be completed per person to four per project. You may complete the Issues that you have already commented in (that did not have comments from other people) but after that, please do not work on any more Issues in this project for now. I will remove the limit in the future when the repo doesn't have so much activity. 

You are free to complete Issues in EmojiPages and EmojiBops, up to four in each project.

Thanks!

**Comment by rubiin** [comment]
@brittanyrw ok sure, i will work on other projects then. Do check my prs

**Comment by spacemonkey1101** [comment]
@brittanyrw can i take it?
