### ISSUE TITLE
Add all of the Rocky movies and review existing Rocky cards

### ISSUE THREAD

**Issue by brittanyrw** [brittanyrw/emojiscreen#228]
Make sure that all of the Rocky movies have been added to EmojiScreen and review the emojis in existing ones to make sure they make sense/are descriptive enough for people to guess when we have game mode created.

Link to all Rocky movies: https://www.imdb.com/list/ls020255449/

**Comment by syn-code** [comment]
could I work on this one?

**Comment by syn-code** [comment]
@brittanyrw does this need to start right away or would it need to be during hacktober?

**Comment by brittanyrw** [comment]
@bladedevleoper There is no rush! Feel free to complete it now or wait until October. It is up to you. You commenting in this Issue saves it for you.  I will make sure to not accept any pull requests for Rocky from other people. 🙂

**Comment by syn-code** [comment]
brilliant, I'll do it in Ocotober, got a few things I need to do before then. It is good practice working with JS objects.

**Comment by syn-code** [comment]
I'll be making a pull this week, an will start to work on this. I cannot merge my changes into your master, so I'm wondering if you have to pull it in ?

**Comment by brittanyrw** [comment]
@bladedevleoper You can create a new pull request now. I had the repo paused for contributions since there was so much activity so I could go through all of the pull requests.
