### ISSUE TITLE
Add link to the movie

### ISSUE THREAD

**Issue by dantehemerson** [brittanyrw/emojiscreen#230]
Add an external link to see more information about the movie. 
It could be IMDB maybe.

**Comment by brittanyrw** [comment]
@dantehemerson That is a really great idea! Did you want to work on any part of adding this to the project yourself? 

I think that using IDMB is a great idea for movies and TV shows. For musicals, there is http://www.playbill.com/vault.

I think breaking this out into a couple of issues would be best. Such as adding this into the JavaScript as one issue and then updating the README, and updating current cards with the IMDB links as additional separate issues.

**Comment by dantehemerson** [comment]
Yeah, I want to contribute with JavaScript feature. Can assign me please.

**Comment by brittanyrw** [comment]
No problem, you are assigned! 👍
