### ISSUE TITLE
Add link for items starting with A & B in the data.js file

### ISSUE THREAD

**Issue by brittanyrw** [brittanyrw/emojiscreen#250]
Add the `itemLink` url for shows/movies that start with A or B in the data.js file.

You can refer to [the link section](https://github.com/brittanyrw/emojiscreen#card-overview) in the README.

For TV shows and movies, add the [IMDB page](https://www.imdb.com/) link.

For musicals link the [Playbill archive page](http://www.playbill.com/vault) for the show. Make sure the Playbill link is for the original production. It will say 'original' under the show name on Playbill. Here is an example of [the page you should be linking](http://www.playbill.com/production/les-miserables-broadway-theatre-vault-0000012257) for musicals.

**Comment by mmikaeleriksson** [comment]
Hello Brittany, really cool project.
Is it ok if I take this issue?

**Comment by brittanyrw** [comment]
@mmikaeleriksson Thanks! And yes, go for it. I will assign it to you. 💖
