### ISSUE TITLE
Add link for items starting with D to F in the data.js file 

### ISSUE THREAD

**Issue by brittanyrw** [brittanyrw/emojiscreen#252]
Add the `itemLink` url for shows/movies that start with D to F in the data.js file.

You can refer to [the link section](https://github.com/brittanyrw/emojiscreen#card-overview) in the README.

For TV shows and movies, add the [IMDB page](https://www.imdb.com/) link.

For musicals link the [Playbill archive page](http://www.playbill.com/vault) for the show. Make sure the Playbill link is for the original production. It will say 'original' under the show name on Playbill. Here is an example of [the page you should be linking](http://www.playbill.com/production/les-miserables-broadway-theatre-vault-0000012257) for musicals.

**Comment by MikeyAlmighty** [comment]
@brittanyrw I volunteer as tribute :smile:

**Comment by colelins** [comment]
@brittanyrw I was too eager and resolved this issue before reading that I shouldn't take issues that were assigned 😞 This PR should've taken at max a day so I thought it would be alright to work on it. Ill make my PR anyway and if you think it is OK to merge please do. If you have a set time you need to wait before reopening please do. Thank you!

P.S I really like the project's idea!
