### ISSUE TITLE
Add link for items starting with H in the data.js file

### ISSUE THREAD

**Issue by brittanyrw** [brittanyrw/emojiscreen#254]
Add the `itemLink` url for shows/movies that start with H in the data.js file.

You can refer to [the link section](https://github.com/brittanyrw/emojiscreen#card-overview) in the README.

For TV shows and movies, add the [IMDB page](https://www.imdb.com/) link.

For musicals link the [Playbill archive page](http://www.playbill.com/vault) for the show. Make sure the Playbill link is for the original production. It will say 'original' under the show name on Playbill. Here is an example of [the page you should be linking](http://www.playbill.com/production/les-miserables-broadway-theatre-vault-0000012257) for musicals.

**Comment by rubiin** [comment]
@brittanyrw i will do this

**Comment by itsmaggiemay** [comment]
if no one is working on this one I like to try it out
