### ISSUE TITLE
Add link for items starting with O & P in the data.js file

### ISSUE THREAD

**Issue by brittanyrw** [brittanyrw/emojiscreen#257]
Add the `itemLink` url for shows/movies that start with O & P in the data.js file.

You can refer to [the link section](https://github.com/brittanyrw/emojiscreen#card-overview) in the README.

For TV shows and movies, add the [IMDB page](https://www.imdb.com/) link.

For musicals link the [Playbill archive page](http://www.playbill.com/vault) for the show. Make sure the Playbill link is for the original production. It will say 'original' under the show name on Playbill. Here is an example of [the page you should be linking](http://www.playbill.com/production/les-miserables-broadway-theatre-vault-0000012257) for musicals.

**Comment by akiraro** [comment]
I can do this

**Comment by markoboy** [comment]
Hello @brittanyrw I will be working on this one.
