### ISSUE TITLE
Change the card styling to look like vintage TV screens

### ISSUE THREAD

**Issue by brittanyrw** [brittanyrw/emojiscreen#269]

**Comment by ghost** [comment]
Hi, by vintage screens, if you mean this (only the screen part):
https://we.graphics/blog/create-a-detailed-vintage-tv-from-scratch-in-photoshop/
Can I try to work on this?

**Comment by brittanyrw** [comment]
@saisriram2710 Yes, I will assign this to you. But let me come up with more details about this before you start. I will update the description with more info soon.
