### ISSUE TITLE
Add all of the Twilight movies and review existing Twilight cards

### ISSUE THREAD

**Issue by brittanyrw** [brittanyrw/emojiscreen#274]
Make sure that all of the Twilight movies have been added to EmojiScreen and review the emojis in existing ones to make sure they make sense/are descriptive enough for people to guess when we have game mode created.

Link to all Twilight movies: https://www.imdb.com/list/ls008821642/

**Comment by navneetsharmaui** [comment]
I will do this.

**Comment by navneetsharmaui** [comment]
@brittanyrw Assign me this Issue.

**Comment by navneetsharmaui** [comment]
@brittanyrw let someone else take this issue.
