### ISSUE TITLE
Add Mr. Robot (TV Show)

### ISSUE THREAD

**Issue by brittanyrw** [brittanyrw/emojiscreen#277]
Add Mr. Robot to EmojiScreen
Link: https://www.imdb.com/title/tt4158110/

**Comment by sumanismcse** [comment]
Can i work on this issue ?

**Comment by Satyam1203** [comment]
I'll do it..

**Comment by brittanyrw** [comment]
@Satyam1203 Someone else has already commented inside of this issue. Please choose something else to add.

**Comment by Satyam1203** [comment]
ok !! I've added "Big Hero 6" movie and created a new pull request, please check that out
