### ISSUE TITLE
Review emojis for accuracy in data.js

### ISSUE THREAD

**Issue by brittanyrw** [brittanyrw/emojiscreen#281]
I am planning on having a game mode for EmojiScreen eventually where a user will guess the cards either with a timer (how many can you guess in a minute) or by how many they can guess out of a certain number (like how many can you guess out of 30). 

We need to make sure that all of the cards are actually guessable.

So would the user be able to guess the show/movie from  the current emojis? Or if they cannot guess but after seeing what the show/movie is the user would agree that those emojis match the show/movie.

Review the data.js file and update the emojis for any of the shows or movies that you think are not clear enough to be guessed. Please only evaluate things you have actually seen, no need to review every single show/movie.

**Comment by amenier** [comment]
Hi, I have a few corrections I'd like to make.
