### ISSUE TITLE
Add Sherlock (TV Show)

### ISSUE THREAD

**Issue by brittanyrw** [brittanyrw/emojiscreen#283]
Link: https://www.imdb.com/title/tt1475582/

**Comment by sumanismcse** [comment]
Can i work on this issue ?

**Comment by adarshBrata** [comment]
Hey @brittanyrw ! Can I work on this issue if its ok?

**Comment by brittanyrw** [comment]
@DeViL3998 Someone has already commented in this issue requesting to add this to the project. Please choose another show to add. Thanks!

**Comment by adarshBrata** [comment]
Sorry, There was no PR that's why I did it. Anyway I also added links for some movies for #259

**Comment by brittanyrw** [comment]
@DeViL3998 No problem! Could you please update your PR by removing the Sherlock object? Then we will be able to merge your link updates. 🙂
