### ISSUE TITLE
Correct bug in expand/hide button on homepage

### ISSUE THREAD

**Issue by brittanyrw** [brittanyrw/emojiscreen#284]
There is an expand/hide button at the bottom right corner of the homepage.

<img width="1369" alt="Screen Shot 2019-09-19 at 9 38 54 AM" src="https://user-images.githubusercontent.com/23530405/65249107-60dab500-dac1-11e9-94de-3052c55fdcca.png">

When you click on the button, it will either expand the card so the title shows for all cards or hide the title. 

The issue is, this is actually toggling the hide and show on individual cards. Therefore, if you have already expanded a card, when you click the button it will hide that card but show the title for other cards that are not expanded yet. See the gif below for this behavior.

![KtQNaR26J7](https://user-images.githubusercontent.com/23530405/65249255-a26b6000-dac1-11e9-83e4-99b503e83398.gif)

To recreate on your own computer, go to emojiscreen.com. Expand one or two of the cards and then click on the reveal button at the bottom. 

Update the logic so that when you click the button to expand all - it expands every single card. And when you click the button to hide all - it hides every single card.

**Comment by ghost** [comment]
Can you give it to me?
