### ISSUE TITLE
Add a 'back to top' button

### ISSUE THREAD

**Issue by brittanyrw** [brittanyrw/emojiscreen#285]
In the same area as the expand button, create a container around both buttons and add a back to top button.

Here is the area I am referring to: 

<img width="1369" alt="Screen Shot 2019-09-19 at 9 38 54 AM" src="https://user-images.githubusercontent.com/23530405/65251004-8ae1a680-dac4-11e9-9358-2538be4d3df8.png">

Here is an example of what this could look like, a vertical container with some kind of background or border, that includes the reveal button and a back to top link. Use font awesome (the free version of icons) for an icon for the back to top button. Example mockup below, the back to top can go above or below the current reveal button:

<img width="541" alt="Screen Shot 2019-09-19 at 10 04 50 AM" src="https://user-images.githubusercontent.com/23530405/65251316-1f4c0900-dac5-11e9-85dc-e5e2c5743dc0.png">

**Comment by globa-clearscale** [comment]
Hi all! If you don't mind, I will do it.

**Comment by globad** [comment]
Hi all! If you don't mind, I will do it.

**Comment by brittanyrw** [comment]
Hi @globad! Sounds good, you have been assigned. Let us know if you need any assistance with anything!

**Comment by globad** [comment]
Thanx!

**Comment by globad** [comment]
> a vertical container with some kind of background or border

@brittanyrw do you want this container to be visible? Usually these things are transparent.

**Comment by brittanyrw** [comment]
@globad It can be transparent.

**Comment by globad** [comment]
@brittanyrw PR is ready, you can review it.
