### ISSUE TITLE
Accessibility Updates

### ISSUE THREAD

**Issue by brittanyrw** [brittanyrw/emojiscreen#29]
Update HTML to make cards accessible

**Comment by mxmason** [comment]
Happy to take this if no one else is interested! Can also refer an associate of mine to this issue :)

**Comment by brittanyrw** [comment]
@dengeist Go for it! 😄

**Comment by kwaimind** [comment]
Not sure if @dengeist is still working on this.

@brittanyrw Can you give a bit more clarity on what kinds of accessibility updates you'd like to see?

**Comment by brittanyrw** [comment]
@kwaimind Sure! Here are some improvements that can be made:

- For the buttons- better and more prominent focus. Right now it is using the default blue focus but it is hard to see. The buttons need to stand out more when you tab onto them.

<img width="267" alt="Screen Shot 2019-09-18 at 3 15 40 PM" src="https://user-images.githubusercontent.com/23530405/65178671-3805e180-da27-11e9-8cc8-f8231f9e63cc.png">

The blue focus works for the card links (the show/movie title that shows when you click on the card is a link) though. This is a new thing I added so not all of them have links yet. A Star is Born is a good example to look at.

- The individual cards need work. I don't think you can access the name of the movie/show or the link to it if you are navigation using the keyboard. Also seems like you can't access the hint either. So this would involve reconfiguring the emoji cards and how they are shown and hidden.

**Comment by jdhrnndz** [comment]
Hello @brittanyrw !

Before I take a stab at this issue. Would you mind confirming that the accessibility improvements you are referring to are mostly visual update? None of the screen-reader or alt-text standards?
