### ISSUE TITLE
Add The Karate Kid (Movie) to EmojiScreen

### ISSUE THREAD

**Issue by brittanyrw** [brittanyrw/emojiscreen#302]
Link: https://www.imdb.com/title/tt0087538/

**Comment by zwolsman** [comment]
I would like to work on. this one 😄

**Comment by brittanyrw** [comment]
@zwolsman It looks like someone else has added the 1984 Karate Kid already. You could add one of these other Karate Kid movies instead:

- The Karate Kid Part II (1986) - https://www.imdb.com/title/tt0091326/ 
- The Karate Kid Part III (1989) - https://www.imdb.com/title/tt0097647/
- The Karate Kid (2010) - https://www.imdb.com/title/tt1155076/

**Comment by vanishedvan** [comment]
https://github.com/brittanyrw/emojiscreen/pull/366

**Comment by ibrahimcaj** [comment]
I would like to work on this one.
