### ISSUE TITLE
Add all of the X-Men movies and review existing X-Men cards to EmojiScreen

### ISSUE THREAD

**Issue by brittanyrw** [brittanyrw/emojiscreen#310]
Make sure that all of the X-Men movies have been added to EmojiScreen and review the emojis in existing ones to make sure they make sense/are descriptive enough for people to guess when we have game mode created.

Link to all X-Men movies: https://www.imdb.com/list/ls026465600/

**Comment by neonvoidx** [comment]
I'd like this one, if you can assign to me, I'll try to get it done by the first and do a pull request @brittanyrw

**Comment by neonvoidx** [comment]
Do you want Deadpool in there as well? its on the list for imdb but obviously isn't xmen

**Comment by brittanyrw** [comment]
@JacobRReed Thanks for working on this! And yes, adding Deadpool is fine as well. 🙂
