### ISSUE TITLE
Add all of the Transformers movies and review existing Transformers cards to EmojiScreen

### ISSUE THREAD

**Issue by brittanyrw** [brittanyrw/emojiscreen#311]
Make sure that all of the Transformers movies have been added to EmojiScreen and review the emojis in existing ones to make sure they make sense/are descriptive enough for people to guess when we have game mode created.

Link to all Transformers movies: https://www.imdb.com/list/ls069544665/

**Comment by susanahan** [comment]
@brittanyrw please assign <3
