### ISSUE TITLE
Add Edward Scissorhands (Movie) to EmojiScreen

### ISSUE THREAD

**Issue by brittanyrw** [brittanyrw/emojiscreen#348]
Link: https://www.imdb.com/title/tt0099487/

**Comment by susanahan** [comment]
@brittanyrw can i work on this?

**Comment by zeny-brus** [comment]
added commit! sorry @susanahan

**Comment by brittanyrw** [comment]
@zeny-brus Please choose something else to add. I am going with the person that commented within the Issue first, since those were the instructions in the repo. Thanks!

**Comment by zeny-brus** [comment]
ooh sorry I had no intentions, I sent other commits thank's

**Comment by brittanyrw** [comment]
@zeny-brus It's no problem! There is a lot of activity on the repo right now so just trying to reduce the number of duplications. 🙂
