### ISSUE TITLE
Add a button to toggle between light and dark theme

### ISSUE THREAD

**Issue by brittanyrw** [brittanyrw/emojiscreen#35]
Add a button (probably in the top right of the page) that will toggle on a dark and light theme.

If you are updating the CSS/styling, make sure that the dark theme works with dark-colored emojis.

**Comment by silvererudite** [comment]
Hi...I would like to get some practice with adding features can this be assigned to me?

**Comment by brittanyrw** [comment]
@silvererudite Thanks for working on this. Yes, it can be assigned to you.

**Comment by silvererudite** [comment]
Hi...I'm having an issue. After cloning the repo, I"m not being able to see the emoji cards when I open the index.html file in browser. here's a screenshot of what I see
![Screenshot (11)](https://user-images.githubusercontent.com/24827548/61581586-18932b00-ab42-11e9-8cbe-02599347d6d7.png)

**Comment by callofdutyin** [comment]
@silvererudite are you still working on this ?, if not @brittanyrw , i would like to take this up
is this possible ?

**Comment by nakulrathore** [comment]
@silvererudite are you still working on this? if not , @brittanyrw i would like to take this up.

**Comment by silvererudite** [comment]
hi @brittanyrw and @nakulrathore ..I'm still working on it. I just got stuck with schoolwork but I'm almost done with it and will submit a PR soon. Sorry for the delay and thanks for being patient.

**Comment by brittanyrw** [comment]
@silvererudite Okay sounds good.

@nakulrathore This same Issue (toggle button for theme) can be added on one of the other projects, EmojiPages or EmojiBops as well if you'd still like to try it! I didn't make this Issue on those projects yet so I can make it on one of them and reserve it for you.

**Comment by nakulrathore** [comment]
@brittanyrw, yes please, make the issue and tag me, 
also, can you describe the required theme a bit coz i see there is already dark background on both of them.
