### ISSUE TITLE
Add Pitch Perfect (Movie) to EmojiScreen

### ISSUE THREAD

**Issue by brittanyrw** [brittanyrw/emojiscreen#359]
Link: https://www.imdb.com/title/tt1981677/

**Comment by rvk7895** [comment]
I would like to work on this for Hacktoberfest .TIA

**Comment by ghost** [comment]
I'll work on it

**Comment by brittanyrw** [comment]
Hi @pranshugrover, this is already assigned it someone else. Please choose another show or movie to add to the project, thanks!

**Comment by ghost** [comment]
Can I work on adding Seinfeld?

**Comment by brittanyrw** [comment]
@pranshugrover
Yep! I have made an Issue for you. Can you comment inside of it so I can assign you?

Link to Issue: https://github.com/brittanyrw/emojiscreen/issues/364
