### ISSUE TITLE
Add difficulty for each card in data.json

### ISSUE THREAD

**Issue by brittanyrw** [brittanyrw/emojiscreen#36]
For game mode, we should allow for users to chose various difficulty levels.
Inside of the data.json file, we need to add a new item to each object called difficulty, which should be a string.

See example:

```
{
 "title":"A Star is Born",
 "emojiImgs":"🎤👩👨🎸⭐",
 "genres":[
  "action",
  "comedy",
  "musical"
 ],
 "type":"movie",
 "year":1994,
 "difficulty": "medium"
}
```

Come up with a criteria for difficulty. It could be, if there are 4 or more emojis, it is easy. If there are three it is medium and if there are one or two it is hard. Or it could be some other criteria. Feel free to run it by me here in the issue before you update code if you would like.

Add difficulty to the current items in the data.json file based on your criteria once that is figured out. And then add a section in the README under Card Overview that explains what difficulty is and what the criteria is.

**Comment by JoelMontano** [comment]
I was thinking the number of emojis would be half of the difficulty and the popularity of the movie could be the other half. The latter would have a heavier weight.

**Comment by renorram** [comment]
@JoelMontano how would you measure the popularity ?

**Comment by KassemOOB** [comment]
No, keep it simple and direct, just add number values(or levels) and you are done

**Comment by JoelMontano** [comment]
> No, keep it simple and direct, just add number values(or levels) and you are done

Yea that's best, thanks!

**Comment by brittanyrw** [comment]
Closing this issue for now.
