### ISSUE TITLE
Add Seinfeld (TV Show) to EmojiScreen

### ISSUE THREAD

**Issue by brittanyrw** [brittanyrw/emojiscreen#364]
Link: https://www.imdb.com/title/tt0098904/

**Comment by brittanyrw** [comment]
This issue is reserved, please do not add this item. Thanks!

**Comment by ghost** [comment]
Thank you. I will add Seinfeld.

**Comment by ghost** [comment]
I am using emojipedia for emojis
what are you guys using?

**Comment by brittanyrw** [comment]
I like https://www.emojicopy.com/ because you can see all of the emojis on one page. 🙂
