### ISSUE TITLE
Add American Horror Story (TV Show) with each season as a different card to EmojiScreen

### ISSUE THREAD

**Issue by brittanyrw** [brittanyrw/emojiscreen#365]
Since American Horror Story is an anthology show (the story and characters change every season), add each individual season as a separate card. If you want to add just one or two seasons that is fine, just comment below which specific season you are adding.

The link for every card should be: https://www.imdb.com/title/tt1844624/
The year for every card should be 2011 (the year that the first season of AHS aired)

American Horror Story: Murder House
American Horror Story: Asylum
American Horror Story: Coven
American Horror Story: Freak Show
American Horror Story: Hotel 
American Horror Story: Roanoke 
American Horror Story: Cult
American Horror Story: Apocalypse 
American Horror Story: 1984

**Comment by CroquetMickael** [comment]
Hi, i will take it !

**Comment by rubiin** [comment]
@brittanyrw I will take this one, will send pr in couple of hours. Also should we be emphasing on the series name too or the season only?

**Comment by brittanyrw** [comment]
@rubiin This Issue is already taken, please choose something else.
