### ISSUE TITLE
Add The Bachelor (TV Show) to EmojiScreen

### ISSUE THREAD

**Issue by brittanyrw** [brittanyrw/emojiscreen#379]
Link: https://www.imdb.com/title/tt0313038/

**Comment by WilChrist** [comment]
I'll handle this.

**Comment by WilChrist** [comment]
For this one the genres are _Drama, Game-Show, Reality-TV_ , but there is no  Game-Show, Reality-TV in the chart you list in your readme. What am i supposed to do? Just write Drama ?
