### ISSUE TITLE
Mobile styling updates

### ISSUE THREAD

**Issue by brittanyrw** [brittanyrw/emojiscreen#38]
Make sure that the styling looks great on more screen sizes.
For example, here is a screenshot of iPhone 5:
<img width="521" alt="Screen Shot 2019-07-17 at 11 42 00 PM" src="https://user-images.githubusercontent.com/23530405/61427563-a675d880-a8ec-11e9-880a-20bf2d6b5de7.png">

On all screens, the emojis should all fit on one line.

**Comment by navneetsharmaui** [comment]
@brittanyrw Why this issue is still open, I see that @systemry420 had made a commit referencing this issue.

**Comment by navneetsharmaui** [comment]
If it's still open I will do this.
