### ISSUE TITLE
Add The IT Crowd (TV Show) to EmojiScreen

### ISSUE THREAD

**Issue by brittanyrw** [brittanyrw/emojiscreen#392]
Link: https://www.imdb.com/title/tt0487831/

**Comment by Manukam** [comment]
Hi, I will work on this.

**Comment by huzairuje** [comment]
can i work on this one too ?

**Comment by Manukam** [comment]
@huzairuje Hi, Please pick another issue.

**Comment by huzairuje** [comment]
ok @Manukam
