### ISSUE TITLE
Add a timed game mode

### ISSUE THREAD

**Issue by brittanyrw** [brittanyrw/emojiscreen#4]
Add a game mode page where users will try to guess as many cards as they can within a specific time limit.

Required:
- Need to add an input that would check the user guess against the emoji card title

**Comment by BadRecordLength** [comment]
Hi, I've made a fair bit of progress with this so if I could be assigned it that'd be great 😁.

**Comment by brittanyrw** [comment]
@BadRecordLength That is awesome! I just assigned you. Thanks for working on this.

**Comment by BadRecordLength** [comment]
@brittanyrw At the moment I'm doing it using VueJS on a new page that's linked on the main page, is that ok? Alternatively, I could hook Vue into the main page as well and just un-render everything on the main page when the user clicks the quiz link, to keep it a single page application, though I feel the previous method is simpler. Thanks 😄.

**Comment by brittanyrw** [comment]
@BadRecordLength I agree, the first one would be better! Let's keep it separate for now.
