### ISSUE TITLE
Add a quiz game mode

### ISSUE THREAD

**Issue by brittanyrw** [brittanyrw/emojiscreen#5]
Add a game mode where users will try to guess emoji cards within a certain number. Such as how many can they guess out of 20.

**Comment by navneetsharmaui** [comment]
Hey @brittanyrw this enhancement sounds fun, can I do this if it's not been started.

**Comment by brittanyrw** [comment]
@navneetsharmaui It looks like you have commented in a lot of Issues. I have decided to limit the number of Issues people can complete on this project to allow as many people as possible to contribute. Could you please pick four of the Issues you have commented in to work on? Let me know as a comment in them and then I will assign them to you!

**Comment by navneetsharmaui** [comment]
@brittanyrw I will do this.
Wouldn't it count as an enhancement?

**Comment by brittanyrw** [comment]
@navneetsharmaui I am doing four total things per project, including enhancements. So for example one enhancement Issue plus three movies or two enhancements and two movies and so on.

**Comment by navneetsharmaui** [comment]
@brittanyrw Greate looking forward to making this enhancement.

**Comment by navneetsharmaui** [comment]
You might already have some ideas how this screen might look like?
