### ISSUE TITLE
Add "Great Expectations" (1998) to EmojiScreen

### ISSUE THREAD

**Issue by Nerdy-Girl** [brittanyrw/emojiscreen#519]
Link: [Great Expectations](https://www.imdb.com/title/tt0119223/)

**Comment by mrillusion** [comment]
I'll sort this one out :)

**Comment by xingwang** [comment]
I'll take this one.

**Comment by brittanyrw** [comment]
@xingwang It looks like this has already been completed. Feel free to choose something else to add, it does not have to be something that has an Issue.
