### ISSUE TITLE
Remove the 'ref' parameter from all of the itemLink values in data.js

### ISSUE THREAD

**Issue by brittanyrw** [brittanyrw/emojiscreen#548]
In data.js, some of the `itemLink` urls have a `ref` parameter that looks like this:
`?ref_=tt_sims_tt`.

Remove the parameter so that the itemLink url is the base url from IMDB. So it should be this: `https://www.imdb.com/title/tt5788792/` instead of `https://www.imdb.com/title/tt5788792/?ref_=tt_sims_tt`.

**Comment by NitinNair89** [comment]
Happy to take this up. :+1:

**Comment by Ayushi0508** [comment]
i want to work on this issue

**Comment by Morsusy2k** [comment]
Can someone assign me the issue?
