### ISSUE TITLE
Update formatting for genres in data.js file

### ISSUE THREAD

**Issue by brittanyrw** [brittanyrw/emojiscreen#549]
Let's make the genre array values more uniform. In the data.js file, format the genre arrays to the following:

- Genres should be all lowercase 
- If genres are two words, they should be separated with a hyphen.

Incorrect genre formatting:
```
genres: ["Action", "True Crime",  "Adventure"]
```

Correct genre formatting:

```
genres: ["action", "true-crime",  "adventure"]
```

Update the `README.md` in the Card Overview section and the `pull_request_template.md` to make the directions more clear for how to format the genres.

**Comment by NitinNair89** [comment]
Happy to take this up. :+1:
