### ISSUE TITLE
Add "Tron: Legacy" (Movie) to emojiscreen

### ISSUE THREAD

**Issue by TechGirl007** [brittanyrw/emojiscreen#556]
Could we add this movie to the emojiscreen?  ;)

https://www.imdb.com/title/tt1104001/

**Comment by jakecinco** [comment]
> Could we add this movie to the emojiscreen? ;)
> 
> https://www.imdb.com/title/tt1104001/

I'm happy to work on this!

**Comment by TechGirl007** [comment]
:(  Was hoping to do this one.  Never mind...I will add another issue!  ;)
