### ISSUE TITLE
Add IMDB list link to EmojiScreen header

### ISSUE THREAD

**Issue by brittanyrw** [brittanyrw/emojiscreen#618]
I have created an IMDB list for all of the EmojiScreen TV shows and movies and will add shows/movies as they are added to the project! Add the link to the IMDB link inside of the header.

Link to IMDB list: https://www.imdb.com/list/ls095903435/

Use the IMDB font awesome icon: https://fontawesome.com/icons/imdb?style=brands

The text should read: View EmojiScreen IMDB List

Add the link like a button similar to the image below as seen on EmojiBops: 
<img width="741" alt="Screen Shot 2019-09-29 at 11 31 12 PM" src="https://user-images.githubusercontent.com/23530405/65847854-40a4c480-e311-11e9-82cf-351eb0b0684f.png">

Feel free to suggest other designs or locations for the links. Let us know if you need more guidance for this issue.

**Comment by raghav-ys** [comment]
@brittanyrw - I would like to work on this.

**Comment by brittanyrw** [comment]
@raghav-ys Great! I have assigned this to you.
