### ISSUE TITLE
Update data.js emoji cards to prep for game mode

### ISSUE THREAD

**Issue by brittanyrw** [brittanyrw/emojiscreen#619]
In preparation for adding a game mode to EmojiScreen (where people will try to guess the show and movie), we need to go through the emojis and make sure that the emojis representing each show/movie actually match the show or movie and that someone would be able to guess that show or movie from the emojis. 

Below is a list of shows/movies that need to be updated:

For the following, update the emojis so they better reflect the TV show, movie or musical:

**America’s Next Top Model**
Current emojis: 👜👭👭

**Bad Santa**
Current emojis: 😁😂🥰🌺🌼

**Buffy the Vampire Slayer**
Current emojis: 🅾️🎃🧛‍

**Catch Me If You Can**
Current emojis: 👋🏃‍🦹‍

**The Cheetah Girls**
Current emojis: 🐆🐆🐆🐆🎶

**Dance Moms**
Current emojis: 💃👯‍🙍‍

**Into the Woods**
Current emojis: 🔥🎄🎶👩‍🎤

**IT: Chapter Two**
Current emojis: 🤡🎈🤡🎈🤡

**Jersey Shore**
Current emojis:  😂🥺🙆‍💔

**La La Land**
Current emojis: 👩👮💓

**Matilda the Musical**
Current emojis:  👸💃🎼

**Mulan**
Current emojis: 🔫⚔️🎶🥁

**Rent**
Current emojis: 🍃🍂🍁♥️

**Rugrats**
Current emojis: 👶🏻👶🏼👶🏻👶🏻👧🏻

**So You Think You Can Dance**
Current emojis: 👦👧🎶💃🕺

**Spiderman**
Current emojis: 😎🕷💪😍

**Tropic Thunder**
Current emojis: 😼😽🙀😿😾

**Comment by nimrodcoder** [comment]
I'd like to work on it.

**Comment by brittanyrw** [comment]
@nimrodcoder Awesome, I will assign this to you!

**Comment by nimrodcoder** [comment]
just one stupid question which i should have asked before, from where are we supposed to pick the emojis? Is there a library you use?

**Comment by brittanyrw** [comment]
@nimrodcoder Not a stupid question at all. I like using https://www.emojicopy.com/ because it lists all of the emojis on one page. And when you click on one, it will add it to the tray at the bottom where you can copy them.

Also if you have a Mac, you can use the keyboard shortcut control + command + space to bring up an emoji keyboard. 

On Windows, I think it is Windows + ; (semi-colon) or Windows + . (period). Or you might have to Google it for your particular operating system.

**Comment by nimrodcoder** [comment]
Thanks, @brittanyrw. Huge Help!!
