### ISSUE TITLE
Add link for items starting with W & Z in the data.js file

### ISSUE THREAD

**Issue by jessicaetiene** [brittanyrw/emojiscreen#638]
**Name of Show or Movie**
List the name of the show or movie here

**Have you confirmed that this has not already been added to the project?**
Check the data.js file, Issues and Pull Requests to make sure you are not adding a duplicate.

**Comment by jessicaetiene** [comment]
I'd like to do this

**Comment by brittanyrw** [comment]
@jessicaetiene Thanks for catching that. I am assigning this to you!
