### ISSUE TITLE
Add movies from Rotten Tomatoes Top 100 Rated Movies

### ISSUE THREAD

**Issue by brittanyrw** [brittanyrw/emojiscreen#642]
Rotten Tomatoes has a list of the top rated movies. Let's add all of these movies to EmojiScreen. Comment below what you want to add before adding anything please so we can avoid duplicates. 

Link to list: https://www.rottentomatoes.com/top/bestofrt/

Below are the movies on the list that have not been added to the project yet.

**Instructions**
Please follow these instructions before adding a movie:
1. Check the [data.js](https://github.com/brittanyrw/emojiscreen/blob/master/data.js) file and the [open pull requests](https://github.com/brittanyrw/emojiscreen/pulls) to make sure the movie hasn't already been added.
2. Comment the movie(s) you want to add below so we can try to avoid duplicates. You can add multiple but not looking for just one person to add all of the movies. 
3. Follow the instructions in the [card overview](https://github.com/brittanyrw/emojiscreen/blob/master/docs/card_overview.md) to add a movie to the project. 
4. If you are adding multiple movies from this list, please include them in one pull request

You do not have to wait for confirmation to add something. We will accept the PR from the person that commented first. 

If something is crossed out, someone else is adding that particular movie.

#'s
12 Angry Men (1957) 
12 Years a Slave (2013)
The 39 Steps (1935) 
~~The 400 Blows (Les Quatre cents coups) (1959)~~  

A
A Hard Day's Night (1964) 
~~A Quiet Place (2018)~~ 
A Streetcar Named Desire (1951) 
The Adventures of Robin Hood (1938) 
All About Eve (1950)
All Quiet on the Western Front (1930) 
Argo (2012)  
Arrival (2016) 

B
The Babadook (2014) 
Baby Driver (2017) 
The Battle of Algiers (La Battaglia di Algeri) (1967) 
Bicycle Thieves (Ladri di biciclette) (The Bicycle Thief) (1949) 
The Big Sick (2017) 
The Big Sleep (1946) 
BlacKkKlansman (2018) 
~~Boyhood (2014)~~ 
The Bride of Frankenstein (1935) 
Brooklyn (2015) 

C
The Cabinet of Dr. Caligari (Das Cabinet des Dr. Caligari) (1920) 
Call Me by Your Name (2018) 
Casablanca (1942) 
~~Chinatown (1974)~~ 
~~Citizen Kane (1941)~~ 
Coco (2017) 

D
The Dark Knight (2008) 
Double Indemnity (1944) 
Dr. Strangelove Or How I Learned to Stop Worrying and Love the Bomb (1964)
~~Dunkirk (2017)~~ 

E
Eighth Grade (2018) 

F
The Florida Project (2017)  

G
The Godfather (1972) 
La Grande illusion (Grand Illusion) (1938) 
Gravity (2013) 

H
Hell or High Water (2016) 

I
Incredibles 2 (2018) 
Inside Out (2015) 
It Happened One Night (1934) 

J
~~The Jungle Book (2016)~~ 

K
Kind Hearts and Coronets (1949)
~~King Kong (1933)~~ 

L
~~Lady Bird (2017)~~ 
The Lady Vanishes (1938) 
Laura (1944) 
Lawrence of Arabia (1962) 
Leave No Trace (2018) 

M 
Mad Max: Fury Road (2015) 
The Maltese Falcon (1941)
Manchester by the Sea (2016)  
~~Metropolis (1927)~~ 
Modern Times (1936) 
Moonlight (2016) 

N
The Night of the Hunter (1955)
North by Northwest (1959) 

P
Paddington 2 (2018) 
The Philadelphia Story (1940) 
~~Psycho (1960)~~ 

R
Rear Window (1954) 
Rebecca (1940) 

S
Selma (2014) 
~~Seven Samurai (1956)~~ 
The Shape of Water (2017) 
~~Singin' in the Rain (1952)~~ 
Snow White and the Seven Dwarfs (1937) 
~~Spider-Man: Homecoming (2017)~~ 
Spotlight (2015) 
Star Wars: Episode VII - The Force Awakens (2015) 
Star Wars: The Last Jedi (2017) 
Sunset Boulevard (1950) 

T
The Third Man (1949) 
Three Billboards Outside Ebbing, Missouri (2017) 
~~Thor: Ragnarok (2017)~~ 
The Treasure of the Sierra Madre (1948) 
Touch of Evil (1958)
Toy Story 2 (1999) 
Toy Story 3 (2010) 
 
V
Vertigo (1958) 

W
War for the Planet of the Apes (2017) 
Won't You Be My Neighbor? (2018) 
Wonder Woman (2017) 

Z
~~Zootopia (2016)~~

**Comment by SalimehHabibi** [comment]
Hi. I add this film. The 400 Blows(LES QUATRE CENTS COUPS)

**Comment by steph-chan** [comment]
I'd like to do Spider-Man: Homecoming and Thor: Ragnarok

**Comment by dmodena** [comment]
Hi, I would like to add The Dark Knight

**Comment by mnvalentine313** [comment]
Hi, I would like to add _Chinatown_ (1974)

**Comment by wdixon2186** [comment]
I would love to add Boyhood.

**Comment by woodledoodle** [comment]
I would like to add Edward Scissorhands

**Comment by woodledoodle** [comment]
Secret Life of Pets

**Comment by luckymurari** [comment]
I would like to add Psycho

**Comment by ninypops** [comment]
Hi, I'd like to have a go at Dunkirk.

**Comment by Ash-Crow** [comment]
Hi, I'd like to add Zootopia.

**Comment by JoemaNequinto** [comment]
Hi, I'd like to add A Quiet Place.

**Comment by yordandev** [comment]
Hi! I'd like to contribute and add King Kong (1933).

**Comment by bianavic** [comment]
Hello, I'd like to add Singin' in the Rain (1952) movie =)

**Comment by tuzun89** [comment]
Hi, I would like to add Lawrence of Arabia.  I hope that is fine, cheers!

**Comment by thewhiteswan** [comment]
Hello! I'd love to do The Godfather (1972).

**Comment by Joseph-Whiunui** [comment]
I would like to do The Adventures of Robin Hood (1938)

**Comment by lyndipc** [comment]
I'll add Toy Story 2 (1999)

**Comment by SpaceShipDev** [comment]
I would like to add Paddington please

**Comment by patriciaDAscientist** [comment]
How about Mean Girls

**Comment by kaustubh2000** [comment]
I would like to do 12 Angry Men

**Comment by kaustubh2000** [comment]
I could do The Dark Knight
