### ISSUE TITLE
Remove 'ref' parameter from URLs in the data.js file

### ISSUE THREAD

**Issue by brittanyrw** [brittanyrw/emojiscreen#688]
In the `data.js` file, under `itemLink`, some of the urls have the `ref` parameter at the end.

Here is an example:

```
{
    title: "Monty Python and the Holy Grail",
    emojiImgs: "🤵🐍⛪🍷",
    genres: ["comedy"],
    type: "movie",
    year: 1975,
    itemLink: "https://www.imdb.com/title/tt0071853/?ref_=nv_sr_1?ref_=nv_sr_1"
  }
```

Go through the `data.js` file and remove everything after the IMDB id number. See below for an example of how this should be updated:

Incorrect `itemLink`:

```
itemLink: "https://www.imdb.com/title/tt0071853/?ref_=nv_sr_1?ref_=nv_sr_1"
```

Correct `itemLink`:

```
itemLink: "https://www.imdb.com/title/tt0071853/"
```

**Comment by taylorpenberthy** [comment]
I would like to work on this!
