### ISSUE TITLE
Movie Dates - Find errors in the data.js file

### ISSUE THREAD

**Issue by brittanyrw** [brittanyrw/emojiscreen#69]
A few movies have the incorrect date listed in the `data.js` file. Update these dates to the correct ones.

**Comment by LautaroLobo12** [comment]
On it!

**Comment by MeisterRed** [comment]
Hi, I would like to have this issue assigned to me. I can look over the data.js file and see if there's any dates that need to be fixed

**Comment by ghost** [comment]
I will work on this!
