### ISSUE TITLE
Add IMDB or Playbill.com URL for missing itemLink in data.js

### ISSUE THREAD

**Issue by brittanyrw** [brittanyrw/emojiscreen#714]
Add `itemLink` to all objects that are missing it in the `data.js` file. 

You can refer to [the link section](https://github.com/brittanyrw/emojiscreen/blob/master/docs/card_overview.md#link-) in the documentation.

For TV shows and movies, add the [IMDB page](https://www.imdb.com/) link.

For musicals link the [Playbill archive page](http://www.playbill.com/vault) for the show. Make sure the Playbill link is for the original production. It will say 'original' under the show name on Playbill. Here is an example of [the page you should be linking](http://www.playbill.com/production/les-miserables-broadway-theatre-vault-0000012257) for musicals.

**Comment by lucacataldo** [comment]
Hey is it cool if I work on this?

**Comment by CamHardy** [comment]
Done

**Comment by CamHardy** [comment]
You closed the issue but rejected my PR? Just assign me the issue as per your readme and I'll re-submit the PR.
