### ISSUE TITLE
Add all of the Harry Potter movies to EmojiScreen and review existing Harry Potter cards

### ISSUE THREAD

**Issue by brittanyrw** [brittanyrw/emojiscreen#73]
Make sure that all of the Harry Potter movies have been added to EmojiScreen and review the emojis in existing ones to make sure they make sense/are descriptive enough for people to guess when we have game mode created. 

List of Harry Potter movies: https://www.imdb.com/list/ls022302521/

**Comment by harsukhdeol** [comment]
Hey @brittanyrw, I just added all the Harry potter movies!
