### ISSUE TITLE
Add all of the Avengers series movies and review existing Avengers cards

### ISSUE THREAD

**Issue by brittanyrw** [brittanyrw/emojiscreen#75]
Make sure that all of the Avengers movies (just the ones titled Avengers, check the Issues for more Marvel movies) have been added to EmojiScreen and review the emojis in existing ones to make sure they make sense/are descriptive enough for people to guess when we have game mode created.

- The Avengers (2012)  - https://www.imdb.com/title/tt0848228/?ref_=ttls_li_tt
- Avengers: Age of Ultron (2015)  - https://www.imdb.com/title/tt2395427/?ref_=ttls_li_tt
- Avengers: Infinity War (2018) - https://www.imdb.com/title/tt4154756/?ref_=ttls_li_tt
- Avengers: Endgame (2019) - https://www.imdb.com/title/tt4154796/?ref_=ttls_li_tt

**Comment by vphilot** [comment]
Can I take this one?
