### ISSUE TITLE
Make sure shows and movies have at least three emojis

### ISSUE THREAD

**Issue by brittanyrw** [brittanyrw/emojiscreen#79]
Go through the `data.js` file and make sure every movie and show has at least three emojis.

**Comment by timrodz** [comment]
I'd like to tackle this one out - Could also try adding some emoji regex type validation to check that there's at least 3?

**Comment by brittanyrw** [comment]
Hi @timrodz! Thanks for working on this. And sure, feel free to add validation.

**Comment by timrodz** [comment]
Thanks, @brittanyrw! Really cool project.

Just wondering re: #294 - Is it okay if I take that one as well?

**Comment by brittanyrw** [comment]
Ah yes, did not see your comments on that one! Yes you can take that one too. I'll respond to you there as well.

**Comment by timrodz** [comment]
Hello! Before proceeding further, I wanted to ask for your thoughts on splitting the genres by new lines:

```js
// Before
{
    title: "Rocky",
    emojiImgs: "🏃‍♂️🥊🕴️",
    genres: ["drama", "sport"],
    year: 1976
}

// After
{
    title: "Rocky",
    emojiImgs: "🏃‍♂️🥊🕴️",
    genres: [
        "drama",
        "sport"
    ],
    year: 1976
}
```
