### ISSUE TITLE
Add all of the Lord of the Rings movies and review existing Lord of the Rings cards

### ISSUE THREAD

**Issue by brittanyrw** [brittanyrw/emojiscreen#96]
Make sure that all of the main Lord of the Rings movies have been added to EmojiScreen and review the emojis in existing ones to make sure they make sense/are descriptive enough for people to guess when we have game mode created. 

List of Lord of the Rings movies: https://www.imdb.com/list/ls025552264/

**Comment by bladedevleoper** [comment]
could I work on this? This is my first hacktoberfest :)

**Comment by shashimalcse** [comment]
i would like to work on it

**Comment by k-cogswell** [comment]
@brittanyrw I can also work on this if you want to assign it to me.
