### ISSUE TITLE
Add all of the Spider-Man movies and review existing Spider-Man cards

### ISSUE THREAD

**Issue by brittanyrw** [brittanyrw/emojiscreen#98]
Make sure that all of the main Spider-Man movies have been added to EmojiScreen and review the emojis in existing ones to make sure they make sense/are descriptive enough for people to guess when we have game mode created. 

List of Spider-Man movies: https://www.imdb.com/list/ls068354783/

**Comment by vishwa9** [comment]
I have started working on this
@brittanyrw  I have made the changes, Not able to raise a pull request
